### ISSUE TITLE
Rendered distances should use a point separator for decimal numbers

### ISSUE THREAD

**Issue by ComFreek** [UniFormal/UFrameIT#7]
E.g. currently it says "11,38 m". If the rest of the UI is in English, we should render "11.38 m".

**Comment by ComFreek** [comment]
@SESch93 I think the current fix of this issue (https://github.com/UniFormal/UFrameIT/commit/acfc025c6d02fe912d27909fcc46060c1ed71a07) fails in some cases*, e.g. if the current *culture* (in .NET terminology) has thousands separators set to commas, then measuring something like 10^6m will lead to `....toString() == "1,000,000m"`, which will then in turn be transformed to `1.000.000m` using the linked changeset. And the latter seems wrong to me.

I *think* the correct solution would be to 

1. undo the changeset,
2. set the current culture in the Unity app (or in each thread) to `en-US`,

     ```
     Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US"); // this should work
     ```
3. and to use `(point1-point2).magnitude.ToString("N2")` for stringifying the distance.

The last point is in accordance with [an offical example by Microsoft](https://docs.microsoft.com/de-de/dotnet/api/system.double.tostring?view=netframework-4.8#System_Double_ToString_System_String_`) and respects the culture for that matter.

*) I think given that UFrameIT will probably be run by other people (reviewer), these cases are actually not just highly improbable corner cases, but might very well appear.

**Comment by SESch93** [comment]
Your absolutely right. This was only a quickfix for the screenshots. Have done the fix when I had no internet-connection but wasn't right to close the issue :) Sorry :)
